// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Budgets__PreviewController from "./budgets/preview_controller"
application.register("budgets--preview", Budgets__PreviewController)

import FormValidatorController from "./form_validator_controller"
application.register("form-validator", FormValidatorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
