require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/obligatory_payments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ObligatoryPayment. As you add validations to ObligatoryPayment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ObligatoryPayment.create! valid_attributes
      get obligatory_payments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      obligatory_payment = ObligatoryPayment.create! valid_attributes
      get obligatory_payment_url(obligatory_payment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_obligatory_payment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      obligatory_payment = ObligatoryPayment.create! valid_attributes
      get edit_obligatory_payment_url(obligatory_payment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ObligatoryPayment" do
        expect {
          post obligatory_payments_url, params: { obligatory_payment: valid_attributes }
        }.to change(ObligatoryPayment, :count).by(1)
      end

      it "redirects to the created obligatory_payment" do
        post obligatory_payments_url, params: { obligatory_payment: valid_attributes }
        expect(response).to redirect_to(obligatory_payment_url(ObligatoryPayment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ObligatoryPayment" do
        expect {
          post obligatory_payments_url, params: { obligatory_payment: invalid_attributes }
        }.to change(ObligatoryPayment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post obligatory_payments_url, params: { obligatory_payment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested obligatory_payment" do
        obligatory_payment = ObligatoryPayment.create! valid_attributes
        patch obligatory_payment_url(obligatory_payment), params: { obligatory_payment: new_attributes }
        obligatory_payment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the obligatory_payment" do
        obligatory_payment = ObligatoryPayment.create! valid_attributes
        patch obligatory_payment_url(obligatory_payment), params: { obligatory_payment: new_attributes }
        obligatory_payment.reload
        expect(response).to redirect_to(obligatory_payment_url(obligatory_payment))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        obligatory_payment = ObligatoryPayment.create! valid_attributes
        patch obligatory_payment_url(obligatory_payment), params: { obligatory_payment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested obligatory_payment" do
      obligatory_payment = ObligatoryPayment.create! valid_attributes
      expect {
        delete obligatory_payment_url(obligatory_payment)
      }.to change(ObligatoryPayment, :count).by(-1)
    end

    it "redirects to the obligatory_payments list" do
      obligatory_payment = ObligatoryPayment.create! valid_attributes
      delete obligatory_payment_url(obligatory_payment)
      expect(response).to redirect_to(obligatory_payments_url)
    end
  end
end
